### ISSUE TITLE
Cfd::profit_btc is fluctating for closed positions

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1183]
Version: 0.3.6

It looks like there is a bug in our profit calculation as the realized PnL in BTC is fluctuating (for closed positions).

https://github.com/itchysats/itchysats/blob/95d8b7c9abb8092813c355a841085b4995ebce41/daemon/src/model/cfd.rs#L618-L635

This graph shows the sum of  profit_btc of all closed positions over time. In this time, there was no additional closed position

![image](https://user-images.githubusercontent.com/224613/150481174-da802865-76b3-4e1d-8c97-fd16e2bf130c.png)

**Comment by da-kami** [comment]
This problem is already be for `0.4.0`. My latest changes here #1182 it should be more correct, but the fluctuation should have already been fixed with Thoma's locking it into the closing price.

I think we should re-evaluate how fast we can ship `0.4.0` on Monday. We are very close to finishing the funding rate, but we still need more testing and bugfixing. I think we should not rush `0.4.0`, but I am not sure it's worth investing into backporting fixes.

**Comment by bonomat** [comment]
Sorry, I don't understand your comment. Are you saying the problem _should have been fixed_ by @thomaseizinger or _will be fixed_ by you in #1182 ?

**Comment by bonomat** [comment]
> I think we should re-evaluate how fast we can ship `0.4.0` on Monday. We are very close to finishing the funding rate, but we still need more testing and bugfixing. I think we should not rush `0.4.0`, but I am not sure it's worth investing into backporting fixes.

Makes sense. Afaik this is just a UI issue. The actual payout in the CETs should be independent of this and is hopefully correct :)

**Comment by bonomat** [comment]
I have a hunch: I was tracking PnL of all CFDs including failed once. It looks like that for failed CFDs the value is not fixed but uses the current price.

**Comment by thomaseizinger** [comment]
> I have a hunch: I was tracking PnL of all CFDs including failed once. It looks like that for failed CFDs the value is not fixed but uses the current price. 
> 

That is fixed in 0.4.0.

**Comment by bonomat** [comment]
> > I have a hunch: I was tracking PnL of all CFDs including failed once. It looks like that for failed CFDs the value is not fixed but uses the current price.
> 
> That is fixed in 0.4.0.

Closing this then
